### ISSUE TITLE
Use skimage instead of opencv

### ISSUE THREAD

**Issue by AbdealiLoKo** [AbdealiJK/file-metadata#22]
OpenCV fails to open animated gif files, XCF files and SVG files.
skimage uses Pillow which can support GIF files and many more formats like eps, pdf, etc that opencv cannot - http://pillow.readthedocs.io/en/3.2.x/handbook/image-file-formats.html

Why skimage ?
- It is very pythonic, it is built on top of numpy/scipy and hence can leverage them easier. For example, to find the average of an image in opencv you use `cv2.mean(im)` but in skimage you just do `im.mean()` as `im` is a numpy ndarray.
  - It can be installed with pip (which is the most important feature it provides)
  - It supports more file formats that opencv, and uses multiple backends for opening and saving file formats.

Hence, it makes sense to use skimage instead of opencv for reading files atleast. Currently, this is the only thing that opencv is being used for.

**Comment by drtrigon** [comment]
Indeed opencv file reading and image format support is bad.

Am 6. Juni 2016 04:32:51 MESZ, schrieb AbdealiJK notifications@github.com:

> OpenCV fails to open animated gif files, XCF files and SVG files.
> skimage uses Pillow which can support GIF files and many more formats
> like eps, pdf, etc that opencv cannot -
> http://pillow.readthedocs.io/en/3.2.x/handbook/image-file-formats.html
> 
> Why skimage ?
> - It is very pythonic, it is built on top of numpy/scipy and hence can
>   leverage them easier. For example, to find the average of an image in
>   opencv you use `cv2.mean(im)` but in skimage you just do `im.mean()` as
>   `im` is a numpy ndarray.
> - It can be installed with pip (which is the most important feature it
>   provides)
> - It supports more file formats that opencv, and uses multiple backends
>   for opening and saving file formats.
> 
> Hence, it makes sense to use skimage instead of opencv for reading
> files atleast. Currently, this is the only thing that opencv is being
> used for.
> 
> ---
> 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/AbdealiJK/file-metadata/issues/22

Dr. Trigon
