### ISSUE TITLE
XCF file handling

### ISSUE THREAD

**Issue by AbdealiLoKo** [AbdealiJK/file-metadata#23]
To convert xcf files to jpg/png/etc the best way seems to be to use imagemagick's python binding `wand`.

This would enable all the raster image analysis on xcf files too

**Comment by drtrigon** [comment]
Yes try that - I had issues back then.

Using imagemagick has the big advantage that we use the same tool as the wiki php code as well (and thus can reproduce results).

Am 6. Juni 2016 04:36:43 MESZ, schrieb AbdealiJK notifications@github.com:

> To convert xcf files to jpg/png/etc the best way seems to be to use
> imagemagick's python binding `wand`.
> 
> This would enable all the raster image analysis on xcf files too
> 
> ---
> 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/AbdealiJK/file-metadata/issues/23

Dr. Trigon

**Comment by AbdealiLoKo** [comment]
Fixed in https://github.com/AbdealiJK/file-metadata/commit/b1424b1c6160894cb94b251ef5ad5fd8aa94c593
