### ISSUE TITLE
SVG file handling

### ISSUE THREAD

**Issue by AbdealiLoKo** [AbdealiJK/file-metadata#24]
Two things need to be done:
- Figure out a method to identify svg files (the mimetype is not sufficient as seen in https://commons.wikimedia.org/wiki/User:AbdealiJKTravis/logs)
- Read the svg and convert it to raster

**Comment by AbdealiLoKo** [comment]
My analysis on the different mimetypes:
- `text/plain` and `text/html`
  If a file does not have `<?xml ...?>` and simply starts with `<svg xmlns...` it is classified as text/plain or test/html. [Example plain](https://upload.wikimedia.org/wikipedia/commons/5/57/Color_icon_white.svg) [Example html](https://upload.wikimedia.org/wikipedia/commons/f/fd/Animated_pendulum.svg). In both cases by adding the `<?xml` I was able to make the file `image/svg+xml`.
  - `text/html` - If html tags are found in the tag, it gets classified as `text/html`. The [example html](https://upload.wikimedia.org/wikipedia/commons/f/fd/Animated_pendulum.svg) file has a `title` tag, while [example plain](https://upload.wikimedia.org/wikipedia/commons/5/57/Color_icon_white.svg) does not. On removing the `<title>` the mime of the [example html](https://upload.wikimedia.org/wikipedia/commons/f/fd/Animated_pendulum.svg) becomes `text/plain`.
  - `text/plain` - If not text/html, it seems to be `text/plain` as fallback
- `application/xml`
  Not sure about this. Apparently image/svg+xml is not a IANA standard, and so maybe application/xml is the "official" mimetype. But image/svg+xml has been proposed and [not yet registered](https://www.w3.org/TR/SVG/mimereg.html)

**Comment by jayvdb** [comment]
What library is used to determine the mimetype?

**Comment by AbdealiLoKo** [comment]
`python-magic` which uses `magic` internally.

**Comment by AbdealiLoKo** [comment]
The accepted answer in the SO question http://stackoverflow.com/questions/15136264/how-can-i-say-a-file-is-svg-without-using-a-magic-number gives a method of finding whether a file is actually svg or not. I tested it on a few files from all the mimetypes mentioned in the last Log. (text/html, text/plain, application/xml) and it detected it correctly. So, I'm planning to use this to detect whether a file is svg or not.

**Comment by drtrigon** [comment]
Is this just libmagic or including other tools?

Am 6. Juni 2016 06:18:49 MESZ, schrieb AbdealiJK notifications@github.com:

> My analysis on the different mimetypes:
> - `text/plain` and `text/html`
>   If a file does not have `<?xml ...?>` and simply starts with `<svg
>   xmlns...` it is classified as text/plain or test/html. [Example
>   plain](https://upload.wikimedia.org/wikipedia/commons/5/57/Color_icon_white.svg)
>   [Example
>   html](https://upload.wikimedia.org/wikipedia/commons/f/fd/Animated_pendulum.svg).
>   In both cases by adding the `<?xml` I was able to make the file
>   `image/svg+xml`.
> - `text/html` - If html tags are found in the tag, it gets classified
>   as `text/html`. The [example
>   html](https://upload.wikimedia.org/wikipedia/commons/f/fd/Animated_pendulum.svg)
>   file has a `title` tag, while [example
>   plain](https://upload.wikimedia.org/wikipedia/commons/5/57/Color_icon_white.svg)
>   does not. On removing the `<title>` the mime of the [example
>   html](https://upload.wikimedia.org/wikipedia/commons/f/fd/Animated_pendulum.svg)
>   becomes `text/plain`.
> - `text/plain` - If not text/html, it seems to be `text/plain` as
>   fallback
> - `application/xml`
>   Not sure about this. Apparently image/svg+xml is not a IANA standard,
>   and so maybe application/xml is the "official" mimetype. But
>   image/svg+xml has been proposed and [not yet
>   registered](https://www.w3.org/TR/SVG/mimereg.html)
> 
> ---
> 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/AbdealiJK/file-metadata/issues/24#issuecomment-223865663

Dr. Trigon

**Comment by AbdealiLoKo** [comment]
Nope, this is just libmagic.

**Comment by drtrigon** [comment]
Nice! That way you can check for invalid syntax in the same step! Cool.

Am 6. Juni 2016 06:34:47 MESZ, schrieb AbdealiJK notifications@github.com:

> The accepted answer in the SO question
> http://stackoverflow.com/questions/15136264/how-can-i-say-a-file-is-svg-without-using-a-magic-number
> gives a method of finding whether a file is actually svg or not. I
> tested it on a few files from all the mimetypes mentioned in the last
> Log. (text/html, text/plain, application/xml) and it detected it
> correctly. So, I'm planning to use this to detect whether a file is svg
> or not.
> 
> ---
> 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/AbdealiJK/file-metadata/issues/24#issuecomment-223866936

Dr. Trigon

**Comment by jayvdb** [comment]
That algorithm needs improvement, as it will scan continuously past the point where any sane information can be detected.

IMO this is a bug in `file`/`magic`, with code at https://github.com/file/file (with .travis.yml) and bug reports at http://bugs.gw.com/my_view_page.php , and should be raised upstream if it hasnt already been raised.  As it uses a data format, it is possibly quite easy to add custom fixes to the database on systems which dont have the latest database (e.g. travis)

Wikipedia mentions http://mark0.net/soft-trid-e.html as an alternative.

However the most commonly used alternative is https://freedesktop.org/wiki/Software/shared-mime-info/ 

For that standard, there is some interesting code in https://github.com/jleclanche/python-mime, https://github.com/mime-types/python-mime-types, https://bitbucket.org/mrtopf/quantumcore.contenttypes and https://pypi.python.org/pypi/z3c.sharedmimeinfo .

It might also be useful to use guessit as part of the heuristics to guess the mimetype (however .. https://github.com/guessit-io/guessit/issues/305)

Also worth checking svg libraries which probably have a simple but efficient "is svg" function in them. e.g. pysvg , svg_model, glsvg, etc.

**Comment by drtrigon** [comment]
If just want to guess, you can use pythons included mimetypes module.
