### ISSUE TITLE
Installation: Add FAQ

### ISSUE THREAD

**Issue by AbdealiLoKo** [AbdealiJK/file-metadata#26]
There are some issues which cannot  be solved automatically. We should make a FAQ to solve such issues.
For example:
-  When doing `pip install --pre file-metadata` and compiling scikit-image, pip said `cython >= 0.21` not found in pypi. probably because it was clashing with the cython in apt-get ?
  - **Solution**: do `pip install --ignore-installed cython` to override the pre-installed cython in apt-get

Is a very specific issue, which neither pip nor cython will be able to solve on their own.

**Comment by drtrigon** [comment]
Can we say it's always safe and the proper thing to run `pip install --ignore-installed cython` as a first command?

**Comment by AbdealiLoKo** [comment]
@drtrigon I don't think so.

For example, if the user has another python package which depends on cython <=0.23 but >= 0.21 then, upgrading your cython (to the highest version on pypi which is 0.24) will break the other python package.
Hence, I think the best option in such cases is a virtualenv which isolates packages.

**Comment by drtrigon** [comment]
Ok. It's safe to say the proper thing is always to use virtualenv, so let's do that.

**Comment by drtrigon** [comment]
Ahh, yes I agree with the FAQ. What about on the wiki? See e.g. my stuff...

**Comment by AbdealiLoKo** [comment]
I was thinking of doing it on readthedocs. @jayvdb What's your opinion ? I've written down a few pros of each:

Pros of readthedocs:
- Has documentation based on release version
- Can auto generate API documentation and link to it (docstrings and doctests are useful)
- Common for python packages in general, i.e. not only for wikimedia users
- Easy for anyone who knows git, or can use github's "edit" feature to edit the wiki with RST markdown.

Pros of mediawiki:
- Anyone can edit even without knowledge of git/github
- More wikimedia user friendly as it would use wiki markup

PS: If we're doing it on mediawiki, I'd rather do it under Manual:Pywikibot than Userspace

**Comment by AbdealiLoKo** [comment]
Concluded that We're doing it on mediawiki and it is already there in the docs

**Comment by jayvdb** [comment]
IMO this package shouldnt have anything about mediawiki/commons in it, and documenting it on rtd would be normal.
The mediawiki related usage of file-metadata should be a separate package.
