### ISSUE TITLE
Max fetch file size

### ISSUE THREAD

**Issue by jayvdb** [AbdealiJK/file-metadata#36]
Idea from #33, and follows #35

Add a max fetch size, and possibly complement that with a min fetch size.
Ideally we use a MediaWiki API query parameter to limit the results by file size.  If it doesnt exist, we should discuss this and possibly raise a feature request.

Some people may feel they can offer to provide free analysis of (newly uploaded) files , but dont want to download very large files because it will drown their network for hours.

This can also help with the Travis builds, as the very large files can effectively halt the job for large periods of time, reducing the number of files processed.  We could have a separate job to process the very large files.

**Comment by drtrigon** [comment]
Thats a good idea but hard to do in a sensible way: you need a mimetype specific limit - but you only now the mimetype for sure after download...
Can may be solved by iteratively downloading bigger parts if needed.

Am 10. Juni 2016 10:17:12 MESZ, schrieb John Vandenberg notifications@github.com:

> Idea from #33, and follows #35
> 
> Add a max fetch size, and possibly complement that with a min fetch
> size.
> Ideally we use a MediaWiki API query parameter to limit the results by
> file size.  If it doesnt exist, we should discuss this and possibly
> raise a feature request.
> 
> Some people may feel they can offer to provide free analysis of (newly
> uploaded) files , but dont want to download very large files because it
> will drown their network for hours.
> 
> This can also help with the Travis builds, as the very large files can
> effectively halt the job for large periods of time, reducing the number
> of files processed.  We could have a separate job to process the very
> large files. 
> 
> ---
> 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/AbdealiJK/file-metadata/issues/36

Dr. Trigon

**Comment by AbdealiLoKo** [comment]
Shouldn't this technically be a task in phabricator ? As in file-metadata we'd simply be using an argument ?

**Comment by jayvdb** [comment]
Yes, it would be best in the bot code, but could also be in the test suite here to avoid long delays processing large files.

**Comment by AbdealiLoKo** [comment]
This has been implemented for wikibot-filemeta-log - although, it makes more sense to have it in pywikibot, as I'd have to reuse that code (Just a small if condition) for the argument in every script, which is not nice
