### ISSUE TITLE
Line drawing detection

### ISSUE THREAD

**Issue by AbdealiLoKo** [AbdealiJK/file-metadata#40]
Found an SO post which gives some heurestic idea.

http://stackoverflow.com/questions/9354744/how-to-detect-if-an-image-is-a-photo-clip-art-or-a-line-drawing

Currently I'm thinking histogram + SVM may be the best way

**Comment by drtrigon** [comment]
You want to train a model for that? How much time will this take?
My algorithm works w/o training. What using it while you try to train a better one as you propose? (I like algo that do not need training - but of course they are often not that reliable)

Am 12. Juni 2016 18:03:22 MESZ, schrieb AbdealiJK notifications@github.com:

> Found an SO post which gives some heurestic idea.
> 
> http://stackoverflow.com/questions/9354744/how-to-detect-if-an-image-is-a-photo-clip-art-or-a-line-drawing
> 
> Currently I'm thinking histogram + SVM may be the best way
> 
> ---
> 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/AbdealiJK/file-metadata/issues/40

Dr. Trigon

**Comment by AbdealiLoKo** [comment]
@drtrigon I'd like to try the learning one too. Not sure how long it'd take, but hardcoding the edge limits can be a backup.

Also, I wanted to mention an important point. In the MVP we had discussed that we would do "Graphic" detection. I'm unable to define what a Graphic is exactly. It seems that the commons community also had the same issue and it has been nominated for discussion [link](https://commons.wikimedia.org/wiki/Commons:Categories_for_discussion/2016/02/Category:Graphics). And in the CFD there have been suggestions to remove that category altogether.

Would it be possible to decide on another category which is similar to Graphics which reflects our goal better ?
I was thinking Line drawings is better - https://commons.wikimedia.org/wiki/Category:Line_drawings
The definition is much clearer - https://en.wikipedia.org/wiki/Line_art and Google search does differentiate them, meaning it is possible to do (with some accuracy)

> Line art or line drawing is any image that consists of distinct straight or curved lines placed against a (usually plain) background, without gradations in shade (darkness) or hue (color) to represent two-dimensional or three-dimensional objects. Line art can use lines of different colors, although line art is usually monochromatic."

**Comment by jayvdb** [comment]
"Line art" works for me.
I am especially interested in detecting logos (cat: PD logos), but line art
is close enough for MVP.

**Comment by drtrigon** [comment]
Is a hard one too.

I define Graphics as NOT Photograph. I think the definition for Photographs is clear. Imagine you get the raw image (no exif at all) and try to figure out whether it's a photo. (IMHO you could go further and write a simple algo and define what graphics are based on the algos outcome only)
I would like to see that, as this was a quite easy and stable one. But you can substitute it if necessary.
Have you tried just to port my old code?

Am 13. Juni 2016 09:31:07 MESZ, schrieb John Vandenberg notifications@github.com:

> "Line art" works for me.
> I am especially interested in detecting logos (cat: PD logos), but line
> art
> is close enough for MVP.
> On 13 Jun 2016 13:12, "AbdealiJK" notifications@github.com wrote:
> 
> > @drtrigon https://github.com/drtrigon I'd like to try the learning
> > one
> > too. Not sure how long it'd take, but hardcoding the edge limits can
> > be a
> > backup.
> > 
> > Also, I wanted to mention an important point. In the MVP we had
> > discussed
> > that we would do "Graphic" detection. I'm unable to define what a
> > Graphic
> > is exactly. It seems that the commons community also had the same
> > issue and
> > it has been nominated for discussion link
> > 
> > https://commons.wikimedia.org/wiki/Commons:Categories_for_discussion/2016/02/Category:Graphics.
> > And in the CFD there have been suggestions to remove that category
> > altogether.
> > 
> > Would it be possible to decide on another category which is similar
> > to
> > Graphics which reflects our goal better ?
> > I was thinking Line drawings is better -
> > https://commons.wikimedia.org/wiki/Category:Line_drawings
> > The definition is much clearer -
> > https://en.wikipedia.org/wiki/Line_art
> > and Google search does differentiate them, meaning it is possible to
> > do
> > (with some accuracy)
> > 
> > Line art or line drawing is any image that consists of distinct
> > straight
> > or curved lines placed against a (usually plain) background, without
> > gradations in shade (darkness) or hue (color) to represent
> > two-dimensional
> > or three-dimensional objects. Line art can use lines of different
> > colors,
> > although line art is usually monochromatic."
> > 
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly, view it on GitHub
> > 
> > https://github.com/AbdealiJK/file-metadata/issues/40#issuecomment-225496735,
> > or mute the thread
> > 
> > https://github.com/notifications/unsubscribe/AAA69FNg81Cjp93I4QdVDioWFYJyemFDks5qLPThgaJpZM4Iz0uD
> > .
> 
> ---
> 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/AbdealiJK/file-metadata/issues/40#issuecomment-225507525

Dr. Trigon
