### ISSUE TITLE
Downloaded binary files need better handling

### ISSUE THREAD

**Issue by jayvdb** [AbdealiJK/file-metadata#45]
See https://github.com/AbdealiJK/file-metadata/issues/44#issuecomment-227437588

I'd like to understand why it is ever necessary to download ffmpeg on Linux?  That is something I would consider more likely needed on Windows, not Linux.  Most Linux users can very easily obtain ffmpeg.  I'm also not liking downloading executable code from http://johnvansickle.com/ffmpeg/releases/ffmpeg-release-x-static.tar.xz , or any http location without verifying pre-fetched md5s, which means it cant just download the 'latest' as you cant store the 'latest' md5 in the repo.  This is one of those security vulnerabilities in the whole externals/ concept, and why the new catimages must use pypi/OS dependencies as a core requirement of this GSOC project.

I can understand using old catimages/externals like functionality to make life easier for users, but they must explicitly opt-in to insecurely obtained binaries being run on their machine.

And even if they have opted-in, any downloading of any dependencies should include logging console message so it is easy to see when a system provided program is not being found, and the location of the downloads should also be logged to the console. (imagine I am on a dialup connection, and the binary takes a long time to startup, so I hit cancel.  I then start it again with different parameters, hoping it will startup quicker, ... but it is only downloading a large binary without telling me, and it is placed somewhere I cant find so that I could do a ftp/http continuation/resume download.  If I recall the old externals system, it had some of these features, but I dont recall which ones.

**Comment by AbdealiLoKo** [comment]
So, the reason I has the ffmpeg downloading was mainly for ease of installation. At that time I did not realize that there were any apt-get dependencies that were needed. Now that we do have a lot of those, I can indeed remove this and add it at the apt-get step.

Will do :+1:

**Comment by jayvdb** [comment]
Is there a minimum version needed for json support. I do remember something like that being mentioned, but completely forgot about it until @drtrigon mentioned it.

Are there other executibles being downloaded?  Can they be downloaded using a dedicated function please, so it is easy to find them.

**Comment by AbdealiLoKo** [comment]
Yes, there is a minimum needed for JSON support. I don't remember it (8.12 i think?). The version in ubuntu precise does not have JSON.

THat was not the reason I download it though. I have a non-JSON parser too : https://github.com/AbdealiJK/file-metadata/blob/master/file_metadata/_compat.py#L13

**Comment by drtrigon** [comment]
> I'd like to understand why it is ever necessary to download ffmpeg on
> Linux?  That is something I would consider more likely needed on
> Windows, not Linux.  Most Linux users can very easily obtain ffmpeg. 
> I'm also not liking downloading executable code from
> http://johnvansickle.com/ffmpeg/releases/ffmpeg-release-x-static.tar.xz
> , or any http location without verifying pre-fetched md5s, which means
> it cant just download the 'latest' as you cant store the 'latest' md5
> in the repo.  This is one of those security vulnerabilities in the
> whole externals/ concept, and why the new catimages must use pypi/OS
> dependencies as a core requirement of this GSOC project.

Because of a lack of features in older code. See my comment there.
I fully agree with we need MD5. I do not with always using the latest as this is insecure and unstable as well. We must use verified and tested versions only.

> I can understand using old catimages/externals like functionality to
> make life easier for users, but they must explicitly opt-in to
> insecurely obtained binaries being run on their machine.

Totally agree, is what happened with patch.exe.

> And even if they have opted-in, any downloading of any dependencies
> should include logging console message so it is easy to see when a
> system provided program is not being found, and the location of the
> downloads should also be logged to the console. (imagine I am on a
> dialup connection, and the binary takes a long time to startup, so I
> hit cancel.  I then start it again with different parameters, hoping it
> will startup quicker, ... but it is only downloading a large binary
> without telling me, and it is placed somewhere I cant find so that I
> could do a ftp/http continuation/resume download.  If I recall the old
> externals system, it had some of these features, but I dont recall
> which ones.

The old tried to be as verbose as possible. Some ppl complained about having to much output... :)
It worked out what solutions were possible for each package, showed them to the user asking which one to do (gave recommendation and kind of order of preference - os package manager usually first) and then, if needed asked for permission to apply patches as well. Everything was within externals folder only - kind of environment. This allowed essentially to do everything as if done by a user manually. Compillations were done on a package level and on import (on need = on import error) by a **init**.py whitch followed a given template.
I'm not sure anymore whether it displayed download sizes... maybe. I rembemer coding such a thing.
Dr. Trigon

**Comment by zhuyifei1999** [comment]
> Can they be downloaded using a dedicated function please, so it is easy to find them.

[utilities.py#L57](https://github.com/AbdealiJK/file-metadata/blob/4ec26a49fa038b7dde525ba7721c99703c48e6e5/file_metadata/utilities.py#L57)

**Comment by jayvdb** [comment]
`download_software = download` ?

**Comment by AbdealiLoKo** [comment]
@jayvdb I didn't understand your last comment. `download()` is a utility function to download any file from the internet.

Other than ffmpeg, exiftool (from the exiftool website) and zxing (from maven) are also downloaded.
There's also a data file used by dlib for facial recognition that's being downloaded.
- ffmpeg - It was meant for ease of installation. I can remove this as we can ask users to install from pkg managers
- exiftool - It was meant for ease of installation. Again, can be done with the package manager ...
- zxing - It was meant for ease of installation. there's no other way to install this other than to ask the user to install maven and use that. So, I think we need this
- dlib's data - There is no alternative than downloading this directly or packaging it inside the pypi package.

I can add md5 hashes for the latter three. For ffmpeg the host of the website has **only** the latest version, and removes all other versions, hence I had no other choice.

I do currently have a INFO level log when it is downloading. I'll make the default log level to INFO to ensure this visible by default.

**Comment by jayvdb** [comment]
Downloading code of the internet should be level "warning" ;)

How do I grep for all downloads of code?

**Comment by drtrigon** [comment]
All download links, md5, etc. should be put into a dict at the beginning of the script or into a seperate script file - easy to maintain.

Am 22. Juni 2016 10:55:42 MESZ, schrieb John Vandenberg notifications@github.com:

> Downloading code of the internet should be level "warning" ;)
> 
> How do I grep for all downloads of code?
> 
> ---
> 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/AbdealiJK/file-metadata/issues/45#issuecomment-227683191

Dr. Trigon

**Comment by AbdealiLoKo** [comment]
Now we only download dlib's data and zxing's jar from the internet.
ZXing's jar files are downloaded inside setup.py using the new setupdeps stuff. Dlib's face data is currently done while running the dlib analysis - mainly because there were some issues with downloading it during setup.py which I have not debugged yet.

**Comment by drtrigon** [comment]
This is generic with respect that we could add more of these deps if needed, right?

**Comment by AbdealiLoKo** [comment]
Yep, each dependency has a class so it can be customized as much as possible

**Comment by jayvdb** [comment]
Downloading all executable code during setup.py resolves this issue imo.
There is still a permissions problem downloading other data at runtime, because it cant be stored in the package data by a non-privilidged user of the library (not a problem in a venv of course), but that isnt a security problem.

**Comment by drtrigon** [comment]
Cool! So we have a proper solution for that and in case we run into a nasty strange case in future we have the dockers as another solution. Well done!

**Comment by jayvdb** [comment]
It seems there are no objections to this being resolved.  New issues for more specific problems should be opened if necessary.
