### ISSUE TITLE
Haarcascades path not the same

### ISSUE THREAD

**Issue by AbdealiLoKo** [AbdealiJK/file-metadata#53]
In Dockerfile.ubuntu we found that opencv installs the haarcascade files in share/opencv/haarcascades instead of share/OpenCV/haarcascade. This is even though my Ubuntu 14.04 system uses `OpenCV`. SO, it seems the path is not standardized ?

I think it makes sense to make a setupdeps.py class for Haarcascades which copies the files from opencv's folder (if possible) or downloads it from OpenCV's github repo into our data folder directly. This would reduce confusion and we would not be relying on OpenCV as much.

**Comment by jayvdb** [comment]
For ubuntu 16 it is `/usr/share/opencv` from `package opencv-data`.

copying the data will mean it isnt updated by the OS, when opencv releases new data.
Are the data files in github much better than the ones shipped by ubuntu?

If github copy isnt better, I think it is better to have a list of known paths where it exists in the OS, and `setup.py` confirms the required files are present.

If github ones are better, copy them into this repo, and use them (if file datestamp is newer than provided by the OS) ?

**Comment by drtrigon** [comment]
Where do we have to issue a bug report to make the path standardized? I assume other code might have same issue as we have too.
Dr. Trigon

**Comment by jayvdb** [comment]
The ubuntu package is likely derived from the debian package, and it they recently changed the ditectiry name to lowercase I would assume they did so intentionally. The debian packaging is version controlled so we can look at the history to see why the change was made. My guess is it was due to a debian policy.

**Comment by AbdealiLoKo** [comment]
Right now, we check the paths with "opencv" and "OpenCV" and it seems to work.

The github ones are not better, they're the same - hence we're just using the ones provided by the OS package

**Comment by drtrigon** [comment]
/usr/lib/python2.7/posixpath.py:77: AttributeError --> https://bpaste.net/show/1054c38a41f6

If `opencv-data` is not installed at all a meaningfull error message should be thrown.

**Comment by AbdealiLoKo** [comment]
Fixed in https://github.com/pywikibot-catfiles/file-metadata/commit/630a7bf72d6f838b06dcd3987eea6d693185908d
