### ISSUE TITLE
Handling templates instead of categories

### ISSUE THREAD

**Issue by AbdealiLoKo** [AbdealiJK/file-metadata#54]
In commons, it is recommend to not add some categories by hand, rather it is suggested to add a template corresponding to it. How do we handle this ? Should I just pint `Template:<>` to the logs ? Or should I continue printing the categories for the sake of the logs ?

@jayvdb

**Comment by jayvdb** [comment]
I think adding the `Template:...` or `{{...|...}}` to the logging is ok.
Can you provide some examples?
I suspect a template is automatically as good as a leaf-category, as the template manages to process.

**Comment by AbdealiLoKo** [comment]
Some examples of templates:
- All the "Created with" stuff - [Template:Created with Inkscape](https://commons.wikimedia.org/wiki/Template:Created_with_Inkscape)
- All the "Taken with" stuff - [Template:Taken with Nikon D300](https://commons.wikimedia.org/wiki/Template:Taken_with_Nikon_D300)
- Location related things - [Template:Location](https://commons.wikimedia.org/wiki/Template:Location), [Template:Location_possible](https://commons.wikimedia.org/wiki/Template:Location_possible)
- NYPL Images - [Template:NYPL-image-full](https://commons.wikimedia.org/wiki/Template:NYPL-image-full)

**Comment by jayvdb** [comment]
`Template:NYPL-image-full` is a bit different from the others, as the uploader should be adding that as part of their default template, with any fields filled in where they can.
Which fields do you think you can populate?

All of the other templates mentioned are indeed populating leaf-categories.

`Template:GPS_EXIF` is also the equivalent to a leaf category, even though it is informational only, as another bot then adds the Location template. (https://commons.wikimedia.org/wiki/Special:Contributions/DschwenBot / https://commons.wikimedia.org/wiki/Commons:Bots/Requests/DschwenBot).
