### ISSUE TITLE
ERROR:root:Error: Could not find or load main class com.google.zxing.client.j2se.CommandLineRunner

### ISSUE THREAD

**Issue by drtrigon** [AbdealiJK/file-metadata#57]
As you can see from the centos docker log on travis https://travis-ci.org/pywikibot-catfiles/docker-file-metadata/jobs/145671019#L2622

This would solve the last issue in https://github.com/pywikibot-catfiles/docker-file-metadata/pull/6

**Comment by AbdealiLoKo** [comment]
This has been found to not be an issue with the code.

If the package is installed with `pip install /path/to/file-metadata` the zxing packages in setup.py are installed in the actual path where pip wants to install the pkg. And then when running the tests with pytest, there is a name clash with the file_metadata in the current folder and the one installed by pip.

Possible workarounds are
- just copy the datafiles from the final destination
- Use `pip install -e` to install zxing to current folder
- Use `python setup.py --help` to trigger the installation of zxing

**Comment by drtrigon** [comment]
Thanks! 2nd implemented in centos-7 docker.
