### ISSUE TITLE
`pip install 'file-metadata>0.1.0'` or `pip install file-metadata --pre` currently not working

### ISSUE THREAD

**Issue by drtrigon** [AbdealiJK/file-metadata#58]
```
  Could not find a version that satisfies the requirement file-metadata==0.1.0.dev99999999999999 (from versions: 0.0.1.dev20160314064516, 0.0.1.dev20160603144056, 0.0.1.dev20160603144066, 0.0.1.dev20160604021332, 0.0.1.dev20160606160002, 0.1.0)
No matching distribution found for file-metadata==0.1.0.dev99999999999999
```

Would be nice to have a working version online, since the one installed 0.1.0 does not work due to an import error with from `file_metadata.utilities import retry`, had to work-a-round with the routine from the Dockerfiles to make test for installation by package management or pip working on travis.

Can we automatically deploy development releases to pypi from travis? E.g. named after the the data of the push or so. That would be great!

**Comment by AbdealiLoKo** [comment]
0.2.0 is now released

**Comment by drtrigon** [comment]
Cool! Thanks!

Can we auto-deploy to pypi?
